name: AdGuardHome

on:
  push:
  schedule:
    - cron:  '4 5 * * 0'
  workflow_dispatch:

jobs:
  build:
    continue-on-error: true
    outputs:
      ADGUARDHOME_VERSION: ${{ steps.find_version.outputs.ADGUARDHOME_VERSION }}
    runs-on: ubuntu-latest
    steps:
      - 
        id: find_version
        name: Find the adguardhome version
        run: echo "::set-output name=ADGUARDHOME_VERSION::$(curl -s "https://api.github.com/repos/AdguardTeam/AdGuardHome/releases/latest" | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/')"
        shell: bash

      - 
        run: echo ${{ steps.find_version.outputs.ADGUARDHOME_VERSION }}

      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - 
        id: check_repo
        run: docker pull ghcr.io/needforspeed/adguardhome:${{ steps.find_version.outputs.ADGUARDHOME_VERSION }}
        continue-on-error: true

      - 
        run: echo ${{ steps.check_repo.outcome }}

      - 
        if: ${{ steps.check_repo.outcome != 'success' }}
        uses: actions/checkout@v2

      - 
        if: ${{ steps.check_repo.outcome != 'success' }}
        name: Get Sources
        run: |
          curl -L -o "/tmp/AdGuardHome_linux_amd64.tar.gz" https://github.com/AdguardTeam/AdGuardHome/releases/download/${{ steps.find_version.outputs.ADGUARDHOME_VERSION }}/AdGuardHome_linux_amd64.tar.gz
          tar -zxvf /tmp/AdGuardHome_linux_amd64.tar.gz
          ls -alr .
          #docker build . -t needforspeed/adguardhome:latest -t needforspeed/adguardhome:${{ steps.find_version.outputs.ADGUARDHOME_VERSION }}
          #docker images

      - 
        if: ${{ steps.check_repo.outcome != 'success' }}
        name: Publish to GitHub Packages
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile.adguardhome
          load: true
          tags: |
            ghcr.io/needforspeed/adguardhome:latest
            ghcr.io/needforspeed/adguardhome:${{ steps.find_version.outputs.ADGUARDHOME_VERSION }}
      -
         if: ${{ steps.check_repo.outcome != 'success' }}
         run: |
           docker push ghcr.io/needforspeed/adguardhome:latest
           docker push ghcr.io/needforspeed/adguardhome:${{ steps.find_version.outputs.ADGUARDHOME_VERSION }}

