name: External Trigger Scheduler

on:
  schedule:
    - cron:  '*/2 * * * *'
  workflow_dispatch:

jobs:
  external-trigger-scheduler:
    runs-on: ubuntu-latest
    steps:
      - name: External Trigger Scheduler
        run: |
          echo "**** latest version ****"
          curl --silent "https://api.github.com/repos/AdguardTeam/AdGuardHome/releases/latest" | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/'
